# Generated by Django 5.2.6 on 2025-09-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('data', models.DateTimeField()),
                ('weather', models.CharField(max_length=25)),
                ('temp', models.IntegerField()),
                ('weatherInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weather.city')),
            ],
        ),
    ]
