# Generated by Django 5.2.6 on 2025-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='data',
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='wind_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='weather',
            field=models.CharField(max_length=10),
        ),
    ]
