# Generated by Django 5.2.6 on 2025-10-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('Russia', 'Moscow'), ('Russia', 'Sochi'), ('USA', 'New York'), ('USA', 'Las Vegas'), ('Japan', 'Kioto')], default='Russia', max_length=25),
        ),
    ]
