# Generated by Django 5.2.6 on 2025-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('Moscow', 'Russia'), ('Russia', 'Sochi'), ('USA', 'New York'), ('USA', 'Las Vegas'), ('Japan', 'Kioto')], default='Russia', max_length=25),
        ),
    ]
