# Generated by Django 5.2.6 on 2025-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('Moscow', 'Moscow'), ('Sochi', 'Sochi'), ('New York', 'New York'), ('Las Vegas', 'Las Vegas'), ('Kioto', 'Kioto')], default='Sochi', max_length=25),
        ),
    ]
