# Generated by Django 5.2.6 on 2025-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Russia', 'Russia'), ('USA', 'USA'), ('Japan', 'Japan')], default='Russia', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='JapanCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tokyo', 'Tokyo'), ('Kioto', 'Kioto')], default='Tokyo', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='RussiaCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Moscow', 'Moscow'), ('Sochi', 'Sochi')], default='Sochi', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='USACity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('New York', 'New York'), ('Las Vegas', 'Las Vegas')], default='New York', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.RemoveField(
            model_name='weatherinfo',
            name='weatherInfo',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='WeatherInfo',
        ),
    ]
