# Generated by Django 5.2.6 on 2025-10-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_country_japancity_russiacity_usacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='japancity',
            old_name='name',
            new_name='nameJapan',
        ),
        migrations.RenameField(
            model_name='russiacity',
            old_name='name',
            new_name='nameRussia',
        ),
        migrations.RenameField(
            model_name='usacity',
            old_name='name',
            new_name='nameUSA',
        ),
    ]
